### ISSUE TITLE
Roll Details

### ISSUE THREAD

**Issue by jbblily** [ksx0330/FVTT-Insane-System#1]
Thank you for your hard works.
I want to suggest you to add details when doing fear roll.
Attributes which is checked as 'fear', add -2 penalty only to fear roll or evade roll. 
I want to have a checkbox which I can manually check if it is a fear roll or not.
Also, I want to add multiple fear attributes in case for campaign pcs. 

개발 수고가 많으십니다. 
공포심으로 설정된 판정은 자동으로 -2 페널티가 들어가고 있습니다. 
공포심으로 설정된 특기는 '공포판정' 이나 '공포심을 특기로 하는 공격행동의 회피판정' 에만 -2 페널티를 붙이기 때문에
시트에 체크 박스를 넣는 등 상황에 따라 조작이 가능하게 하였으면 좋겠습니다. 
또, 지속 PC의 경우 공포심이 여러개인 상황이 발생하므로 공포심을 여러개 설정할 수 있도록 설정 가능하게 되었으면 좋겠습니다.

**Comment by ksx0330** [comment]
up to date in 0.0.2
